version: '3.8'
services:
  monitoring-db:
    image: postgres:alpine3.19
    env_file:
      - ../../monitoring-backend/.env
    ports:
      - 5433:5432
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
